### ISSUE TITLE
Napravi metodu refresh enumeracije

### ISSUE THREAD

**Issue by lukagulin** [pa1511/TestGenerator#3]
`		public void refreshAnswerNumeration(@Nullable Question question)
		{
			//popravi enumeraciju posli delete
		}`

Ne kužin kako se iz Kolekcije izvuče redni broj

**Comment by pa1511** [comment]
I have made a simple implementation that I think should work.
Please verify the implementation.
I think we don't actually need the position field in the answer because that information is stored as part of a question list so I would suggest getting rid of it.
A answer having a position outside of the kontekst of a question does not make sense!

**Comment by lukagulin** [comment]
"Outside of kontekst" :D

We need it because when generating test we need to remember how answers are scrambled.
